#!/usr/bin/env bash
# Builds the portable command skills in .agents/skills/ from the Claude Code command skills in skills/.
# Claude Code keeps /foreigner:frame and friends. Other agents (Codex, Copilot, Cursor, Gemini CLI and
# more, installed with `npx skills add`) get foreigner-frame and friends, which find the router in the
# sibling folder ../foreigners-pov/ instead of ${CLAUDE_PLUGIN_ROOT}.
# Run from the repo root after editing any command skill. Don't edit .agents/skills/ by hand.
# Optional argument: a different output folder (the copy lint uses this to check the files are in sync).
set -euo pipefail

src_root="skills"
out_root="${1:-.agents/skills}"
router="foreigners-pov"

[ -d "$src_root/$router" ] || { echo "Run this from the repo root." >&2; exit 1; }
mkdir -p "$out_root"
# Remove only what this script made, so a wrong argument can't delete anything else.
rm -rf "$out_root"/foreigner-*

count=0
for dir in "$src_root"/*/; do
  dir="${dir%/}"
  cmd="$(basename "$dir")"
  [ "$cmd" = "$router" ] && continue
  src="$dir/SKILL.md"
  [ -f "$src" ] || continue

  # Frontmatter fields we need from the source.
  desc=""
  hint=""
  in_fm=0
  body=""
  fm_done=0
  while IFS= read -r line || [ -n "$line" ]; do
    if [ "$fm_done" -eq 0 ] && [ "$line" = "---" ]; then
      if [ "$in_fm" -eq 0 ]; then in_fm=1; continue; else fm_done=1; continue; fi
    fi
    if [ "$fm_done" -eq 0 ]; then
      case "$line" in
        description:*) desc="${line#description: }"; desc="${desc#\"}"; desc="${desc%\"}" ;;
        argument-hint:*) hint="${line#argument-hint: }" ;;
      esac
    else
      body+="$line"$'\n'
    fi
  done < "$src"

  # Make the body portable.
  body="${body//\$\{CLAUDE_PLUGIN_ROOT\}\/skills\/$router\//../$router/}"
  body="${body//\$ARGUMENTS/what the user wrote with this command}"
  # Claude Code plugin agents become generic subagents, with a fallback.
  from='start one `foreigner:preflight-runner` agent per item in the same turn so they run in parallel'
  to='start one subagent per item in the same turn so they run in parallel, if your agent has subagents; otherwise go one item at a time'
  body="${body//"$from"/$to}"
  from="Use the \`foreigner:war-room\` agent if it's available"
  to='Use a separate subagent for the war room if your agent has subagents'
  body="${body//"$from"/$to}"
  nl=$'\n'
  body="${body#"$nl"}"

  name="foreigner-$cmd"
  out="$out_root/$name"
  mkdir -p "$out/agents"
  {
    echo "---"
    echo "name: $name"
    echo "description: \"Foreigner's POV command. $desc Run it only when the user calls it by name.\""
    echo "license: MIT"
    echo "disable-model-invocation: true"
    [ -n "$hint" ] && echo "argument-hint: \"$hint\""
    echo "metadata:"
    echo "  generated-from: $src"
    echo "---"
    echo
    echo "<!-- Generated by scripts/build-portable.sh from $src. Edit that file and run the script; don't edit this one. -->"
    echo
    echo "This command is part of Foreigner's POV. Paths starting with \`../$router/\` are relative to this skill's folder: the \`$router\` skill sits next to it. If it isn't there, look for a skill named \`$router\` in your skills folders. If it isn't installed, say so in one line and give the install command: \`npx skills add ForeignerfromJupiter/foreigners-pov\`."
    echo
    printf '%s' "$body"
  } > "$out/SKILL.md"
  {
    echo "# Codex: run this command only when the user calls \$$name."
    echo "interface:"
    echo "  display_name: \"Foreigner's POV: $cmd\""
    echo "policy:"
    echo "  allow_implicit_invocation: false"
  } > "$out/agents/openai.yaml"
  count=$((count + 1))
done

echo "Built $count portable command skills in $out_root/."
